name: Plugin Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.ini'
      - '**.js'
      - '**.html'

env:
  PLUGIN_NAME: 'input-overlay'

jobs:
  clang_check:
    name: 01 - Code Format Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install clang-format
        run: sudo apt-get install -y clang-format-13

      - name: Run clang-format
        run: ./.github/scripts/check-format.sh && ./.github/scripts/check-changes.sh

      - name: Install cmake-format
        run: sudo pip install cmakelang

      - name: Run cmake-format
        run: ./.github/scripts/check-cmake.sh

  linux_build:
    name: 02 - Linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        arch: [x86_64]
    if: always()
    needs: [clang_check]
    outputs:
      commitHash: ${{ steps.setup.outputs.commitHash }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin
          submodules: recursive

      - name: Checkout obs-studio
        uses: actions/checkout@v3
        with:
          repository: 'obsproject/obs-studio'
          path: obs-studio
          fetch-depth: 0
          submodules: recursive

      - name: Setup Environment
        working-directory: ${{ github.workspace }}/plugin
        id: setup
        run: |
          ## SETUP ENVIRONMENT SCRIPT
          echo "ccacheDate=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT
          echo "commitHash=$(git rev-parse HEAD | cut -c1-9)" >> $GITHUB_OUTPUT

      - name: Restore Compilation Cache
        id: ccache-cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: linux-${{ matrix.arch }}-ccache-plugin-${{ steps.setup.outputs.ccacheDate }}
          restore-keys: |
            linux-${{ matrix.arch }}-ccache-plugin-

      - name: Check for GitHub Labels
        id: seekingTesters
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ## GITHUB LABEL SCRIPT
          if [[ -n "$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s "${{ github.event.pull_request.url }}" | jq -e '.labels[] | select(.name == "Seeking Testers")')" ]]; then
            echo 'found=true' >> $GITHUB_OUTPUT
          else
            echo 'found=false' >> $GITHUB_OUTPUT
          fi

      - name: Build Plugin
        uses: ./plugin/.github/actions/build-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo

      - name: Package Plugin
        uses: ./plugin/.github/actions/package-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo

      - name: Upload Build Artifact
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLUGIN_NAME }}-linux-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}
          path: ${{ github.workspace }}/plugin/release/${{ env.PLUGIN_NAME }}-*-linux-${{ matrix.arch }}.*
      - name: Upload binary zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLUGIN_NAME }}-linux-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}
          path: ~/.config/obs-studio/plugins/${{ env.PLUGIN_NAME }}
      - name: Upload preset zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLUGIN_NAME }}-${{ steps.setup.outputs.commitHash }}-presets
          path: ${{ github.workspace }}/plugin/presets
  windows_build:
    name: 02 - Windows
    runs-on: windows-2022
    strategy:
      fail-fast: true
      matrix:
        arch: [x86, x64]
    if: always()
    needs: [clang_check]
    outputs:
      commitHash: ${{ steps.setup.outputs.commitHash }}
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin
          submodules: recursive

      - name: Checkout obs-studio
        uses: actions/checkout@v3
        with:
          repository: 'obsproject/obs-studio'
          path: obs-studio
          fetch-depth: 0
          submodules: recursive

      - name: Setup Environment
        working-directory: ${{ github.workspace }}/plugin
        id: setup
        run: |
          ## SETUP ENVIRONMENT SCRIPT
          $CommitHash = (git rev-parse HEAD)[0..8] -join ''
          "commitHash=${CommitHash}" >> $env:GITHUB_OUTPUT

      - name: Check for GitHub Labels
        id: seekingTesters
        working-directory: ${{ github.workspace }}/plugin
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ## GITHUB LABEL SCRIPT
          $LabelFound = try {
            $Params = @{
              Authentication = 'Bearer'
              Token = (ConvertTo-SecureString '${{ secrets.GITHUB_TOKEN }}' -AsPlainText)
              Uri = '${{ github.event.pull_request.url }}'
              UseBasicParsing = $true
            }

            (Invoke-RestMethod @Params).labels.name.contains('Seeking Testers')
          } catch {
            $false
          }

          "found=$(([string]${LabelFound}).ToLower())" >> $env:GITHUB_OUTPUT
      - name: Build Plugin
        uses: ./plugin/.github/actions/build-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo
          visualStudio: 'Visual Studio 17 2022'

      - name: Package Plugin
        uses: ./plugin/.github/actions/package-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo

      - name: Upload Build Artifact
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLUGIN_NAME }}-windows-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}
          path: ${{ github.workspace }}/plugin/release/${{ env.PLUGIN_NAME }}-*.zip

      - name: Package Plugin Installer
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' }}
        uses: ./plugin/.github/actions/package-plugin
        with:
          workingDirectory: ${{ github.workspace }}/plugin
          target: ${{ matrix.arch }}
          config: RelWithDebInfo
          createInstaller: true

      - name: Upload Installer Artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLUGIN_NAME }}-windows-${{ matrix.arch }}-${{ steps.setup.outputs.commitHash }}-installer
          path: ${{ github.workspace }}/plugin/release/${{ env.PLUGIN_NAME }}-*.exe

  make-release:
    name: 03 - Create and upload release
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: [linux_build, windows_build]
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin
          submodules: recursive

      - name: Get Metadata
        id: metadata
        run: |
          ## METADATA SCRIPT
          echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          echo "pluginName=$(jq -r '.name' buildspec.json)" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Generate Checksums
        run: |
          ## CHECKSUM GENERATION SCRIPT
          shopt -s extglob
          echo "### Checksums" > ${{ github.workspace }}/CHECKSUMS.txt
          for file in ${{ github.workspace }}/**/@(*.pkg|*.exe|*.deb|*.zip); do
            echo "    ${file##*/}: $(sha256sum "${file}" | cut -d " " -f 1)" >> ${{ github.workspace }}/CHECKSUMS.txt
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          draft: false
          prerelease: ${{ contains(steps.metadata.outputs.version, 'rc') || contains(steps.metadata.outputs.version, 'beta') }}
          tag_name: ${{ steps.metadata.outputs.version }}
          name: "${{ env.PLUGIN_NAME }} ${{ steps.metadata.outputs.version }}"
          body_path: ${{ github.workspace }}/CHECKSUMS.txt
          files: |
            ${{ github.workspace }}/**/*.zip
            ${{ github.workspace }}/**/*.exe
            ${{ github.workspace }}/**/*.deb
